steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/wolfchat-fcb50/wolfchat', '.']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/wolfchat-fcb50/wolfchat']
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'run'
  - '--image=eu.gcr.io/wolfchat-fcb50/wolfchat'
  - '--location=europe-west3-a'
  - '--cluster=wolfchat-web-cluster1'